version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: 'postgres-java'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=javadb'